Componente login
EliasMaDeRe/FleetWise pull request #14
Opened 2023-09-26 23:50 UTC by pgamboan

### Descripcion

- constantes.go
- iniciodesesioncontrolador.go
- iniciodesesionmanejador.go

2023-10-04 19:42 UTC, EliasMaDeRe commented on fuente/iniciodesesion/constantes/constantes.go
> +	ERROR_CREDENCIALES_INVALIDAS = "Credenciales inválidas"
Vamos a mantener consistencia usando `"Error: "mensaje"` en las constantes de error

2023-10-04 19:45 UTC, EliasMaDeRe commented on fuente/iniciodesesion/controlador/iniciodesesioncontrolador.go
> +	"tuaplicacion/modelos"
Revisa este import, me parece que no coincide con el .mod de el repo

2023-10-04 19:46 UTC, EliasMaDeRe commented on fuente/iniciodesesion/controlador/iniciodesesioncontrolador.go
> +type InicioDeSesionControlador struct {
Para mantener consistencia en los servicios vamos a usar `Controlador` en lugar de `InicioDeSesionControlador`

2023-10-04 19:48 UTC, EliasMaDeRe commented on fuente/iniciodesesion/controlador/iniciodesesioncontrolador.go
> +func (c *InicioDeSesionControlador) IniciarSesion(c *gin.Context, solicitud modelos.InicioDeSesionSolicitud) {
Vamos a crear un objeto de respuesta que devuelva el controlador al Manejador, para que el Manejador sea el único que trabaja con el JSON / los request http

2023-10-04 19:48 UTC, EliasMaDeRe commented on fuente/iniciodesesion/controlador/iniciodesesioncontrolador.go
> +		c.JSON(http.StatusUnauthorized, gin.H{"error": constantes.ERROR_SESION_NO_INICIADA})
Lo mismo del ultimo comentario

2023-10-04 19:49 UTC, EliasMaDeRe requested changes
Comentarios

2023-10-05 00:00 UTC, pgamboan commented on fuente/iniciodesesion/constantes/constantes.go
> +	ERROR_CREDENCIALES_INVALIDAS = "Credenciales inválidas"
listo

2023-10-05 04:08 UTC, EliasMaDeRe commented on fuente/iniciodesesion/manejador/iniciodesesionmanejador.go
> +	var solicitud := modelos.InicioDeSesionSolicitud
el import modelos funciona correctamente aqui?

2023-10-05 04:08 UTC, EliasMaDeRe commented
Voy a esperar a que revisemos lo de respuesta para estampar

2023-10-19 08:17 UTC, EliasMaDeRe approved these changes
Estampado

2023-10-19 08:17 UTC, merged