[CS-32] Terminando Create y Read de Tipos de Serivicio
EliasMaDeRe/FleetWise pull request #20
Opened 2023-10-26 14:43 UTC by EliasMaDeRe

Eliminar y Editar TBA

2023-11-01 04:57 UTC, FernandoVS11 requested changes

2023-11-01 04:57 UTC, FernandoVS11 commented on modelos/capturaserviciovehicular/capturaserviciovehicular.go
> +	NombreActual string `json:"nombreactual"`
No creo que sea necesario el NombreActual, para editar un servicio en la base de datos tengo entendido que la función es como un Update, entonces solo debes con un where decir que campo se va a editar y pasarle el nuevo valor

2023-11-03 23:15 UTC, EliasMaDeRe commented on modelos/capturaserviciovehicular/capturaserviciovehicular.go
> +	NombreActual string `json:"nombreactual"`
Para el where sería Servicio Vehicular where Nombre == "NombreActual" , osea, ese es el nombre del servicio a actualizar.

2023-11-05 05:42 UTC, CarlosJCD commented on styles/app.css
> +  box-shadow: 0 0 .4rem --rgb_card;
no tienes que poner `var(--rgb_card) ` aquí? te funciona el sombreado así?

2023-11-05 06:05 UTC, CarlosJCD requested changes
Buen trabajo, solamente detecte un par de detalles respecto al CSS y al JS. Porfavor revisalos y de ser necesario haz los cambios sugeridos 🙂

2023-11-05 06:05 UTC, CarlosJCD commented on js/capturaServicioVehicular.js
> +      `
```suggestion
      const encabezadoTarjeta = document.createElement('h3');
      encabezadoTarjeta.classList.add('card__heading');
      
      encabezadoTarjeta.innerText = datosTarjeta.Nombre;
      
      elementoTarjeta.appendChild(encabezadoTarjeta);
```

Deberiamos de intentar evitar crear nuevos elementos html por medio de innerHTML y mejor usar nodos.

2023-11-11 11:09 UTC, EliasMaDeRe commented on styles/app.css
> +  box-shadow: 0 0 .4rem --rgb_card;
true.

2023-11-11 11:10 UTC, EliasMaDeRe commented on js/capturaServicioVehicular.js
> +      `
Se está agregando innerHTML para la tarjeta nada más. Creo que es un uso aceptable de innerHTML

2023-11-22 03:05 UTC, CarlosJCD commented on .env.example
> +# QUITAR EL .EXAMPLE AL FINAL DEL NOMBRE DE ESTE ARCHIVO Y PONER EL TEXTO A REEMPLAZAR ABAJO SIN COMILLAS (AUNQUE SEAN NUMEROS)
En vez de solo quitar el .example, es mejor especificar que dupliquen el archivo y luego quiten el .example de ese archivo duplicado.

2023-11-22 05:27 UTC, FernandoVS11 commented on fuente/conectorbd/controlador/conectorbdcontrolador.go
> +	resultGuardarServicioVehicular := database.Create(
en vez de result cambiarlo a resultado, ya que tamos haciendo todo en español

2023-11-22 05:27 UTC, FernandoVS11 approved these changes

2023-11-22 05:46 UTC, EliasMaDeRe commented on fuente/conectorbd/controlador/conectorbdcontrolador.go
> +	resultGuardarServicioVehicular := database.Create(
Buen catch. Gracias

2023-11-22 06:18 UTC, EliasMaDeRe commented on .env.example
> +# QUITAR EL .EXAMPLE AL FINAL DEL NOMBRE DE ESTE ARCHIVO Y PONER EL TEXTO A REEMPLAZAR ABAJO SIN COMILLAS (AUNQUE SEAN NUMEROS)
done

2023-11-22 06:19 UTC, EliasMaDeRe commented
Mergeando tras resolver comentarios.

2023-11-22 06:19 UTC, merged